name: cypress tests
on:
  push:
    branches: 
      - 'master'
  workflow_dispatch:

jobs:
  checkout-and-tests:
    runs-on: ubuntu-latest
    steps: 
      -run: echo "The auto-test is executing"

      -name: Checkout repository code
       uses: actions/checkout@v2

      -name: run cypress tests with chrome
       uses: cypress-io/gitaction@v2 
       timeout-minute: 10
       with: 
        browser: chrome
      