name: cypress tests
on:
  push:
    branches: 
      - 'master'
  workflow_dispatch:

jobs:
  checkout-and-tests:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "The auto-test is executing"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run with env
        uses: cypress-io/github-action@v4
        with: 
         browser: chrome
      